### ISSUE TITLE
Placeholder for single component does not allow adding components under that component.

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#139]
**Description**
Placeholder for single component does not allow adding components under that component.

**Steps to reproduce**
Example adding a new container to Parent with one child:

![1container](https://user-images.githubusercontent.com/170312/221407308-8e1a6e19-260c-498b-89f2-e27c146c1d53.gif)

Example adding a new container to parent with 2 children child:

![2containers](https://user-images.githubusercontent.com/170312/221407366-61ff19a7-6deb-42c0-9566-bb39591dbe19.gif)

Would be great to avoid copying components.

The container has the template for ${!resource.hasChildren}

  <sly data-sly-test="${!resource.hasChildren}">
    <sly data-sly-use.lib="/libs/wcm/foundation/components/commons/templates.html"
      data-sly-call="${lib.placeholder @ classes=CSSclasses}">
    </sly>
  </sly>

Even if you output this all the time its not printing the placeholder under the component for placing components.
Would be great to allow placeholder for above and under components.

**Comment by paweljozwicki** [comment]
Hi, our placeholder is visible only in empty containers, and usually, we add some additional styles with extra padding for containers in edit mode. E.g. in Howlite, it should be possible to add the next component in the same container by moving out of the existing one:
![Untitled](https://user-images.githubusercontent.com/109656376/221862166-909a6262-14ab-42d3-a071-28285088d0a9.gif)


There is also an "Add" toolbar action in our plans, so authors could choose a container and add a new component from the toolbar action instead of using drag-and-drop.

**Comment by wildone** [comment]
Is it possible to make place holder appear all the time?

**Comment by wildone** [comment]
See example "Example adding a new container to parent with 2 children child" not matter how I try this it does not seem to work.

**Comment by paweljozwicki** [comment]
We will ask our UX designer to look at such a solution. It seems like something that could help with the authoring experience, but we must analyze all the pluses and cons.

**Comment by paweljozwicki** [comment]
It's resolved in [WebSight CMS 1.22.0](https://docs.websight.io/cms/release-notes/#1220-nov-6-2023) From now on, dropping a component into the outer 25% of an empty container area leads to placement in its parent:
![15330dd2-5cba-44f9-b133-63c2bc3352a1](https://github.com/websight-io/starter/assets/109656376/16fb5b78-2394-409d-9c99-ca944011dd3a)
