### ISSUE TITLE
View published link/button

### ISSUE THREAD

**Issue by kamil-kwarciak** [websight-io/starter#23]
View published link/button to be able to quickly jump 

from: http://localhost:8080/apps/websight/index.html/content/luna/pages/Homepage::editor
to: http://localhost:8080/content/luna/pages/Homepage.html

![image](https://user-images.githubusercontent.com/106810068/194580968-b4aee690-c180-4379-8c43-5bef9d8d6ebb.png)

**Additional context**
- Reported by @pun-ky in https://github.com/websight-io/starter/discussions/11

**Comment by michalcukierman** [comment]
Actually, the link should be to:
`http://localhost/Homepage.html`, or even `http://localhost`

`http://localhost:8080/content/luna/pages/Homepage.html` is still rendered on Sling-based engine, where localhost:80 is handled by Nginx. 
This may be tricky to implement, because:
- Nginx may have its own rules for structuring the site. 
- It will be different on DXP, where the Nginx may be replaced with i.e. Vert.x-based solution or using cloud LB instead.

I agree that the functionality is desired, we just need to think about where it should be implemented.
Maybe we could have a Nginx component, which will handle the redirect, as it's the Load Balancer responsibility to create final URL, not CMS one.

Something like:
`localhost:80/whereis?page=/content/luna/Pages/Homepage.html` which will result in `302` redirect to localhost:80.
@pawel-boguski-ds  maybe this component should be used for the URL's shortening in the publishing framework (unlikely, but worth to discuss).


@tomaszmichalak @malaskowski  FYI

**Comment by michalcukierman** [comment]
The decision to make: What should be the SSoT for domains/paths configurations? Do we need SSot?

**Comment by paweljozwicki** [comment]
Introduced in [WebSight CMS 1.20.0](https://docs.websight.io/cms/release-notes/#1200-sep-13-2023)
