### ISSUE TITLE
Maven wrapper support

### ISSUE THREAD

**Issue by rgrebski** [websight-io/starter#7]
How about using Maven wrapper ? You could get rid of 1 step in developer manual. 
I am talking about this:
https://maven.apache.org/wrapper/

**Comment by michalcukierman** [comment]
Local Maven installation is required because we do generate projects using the Maven archetype:
https://www.websight.io/docs/developers/create-and-develop-project/

Nevertheless, I agree that our public repositories (which you can clone using git) should contain Maven Wrapper to simplify setup. We'll add it to `starter`, `howlite`, and other future projects

**Comment by michalcukierman** [comment]
Fixed with the PR: https://github.com/websight-io/starter/pull/8
